---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postg-server
spec:
  selector:
    matchLabels:
      app: postg-server
  replicas: 1
  template:
    metadata:
      labels:
        app: postg-server
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres
        ports:
        - containerPort: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postg-server
spec:
  ports:
  - port: 9042
    name: postgres-port
    targetPort: 9042
    protocol: TCP
  selector:
    app: postg-server
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empire-hq
spec:
  selector:
    matchLabels:
      app: empire-hq
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-hq
    spec:
      containers:
      - name: empire-hq
        image: docker.io/postgres
        command: ["sleep"]
        args: ["30000"]
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empire-outpost
spec:
  selector:
    matchLabels:
      app: empire-outpost
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-outpost
    spec:
      containers:
      - name: empire-outpost
        image: docker.io/postgres
        command: ["sleep"]
        args: ["30000"]